APP_TITLE = "Cosmetic Analysis Tool"
APP_VERSION = "0.4.0"

WINDOW_GEOMETRY = "1440x900"
WINDOW_MIN_SIZE = (1120, 760)

MARKER_SIZE_MM = 30.0

DEFAULT_SAVE_ROOT = "inspections"
CREATE_UNIQUE_SAVE_FOLDER = True

SCRATCH_MIN_SAMPLE_SPACING_MM = 3.0

EXPORT_WRITE_ORIGINAL = True
EXPORT_WRITE_OVERLAY = True
EXPORT_WRITE_JSON = True